create TABLE BLACKLIST (
  USERNAME VARCHAR(10) not null,
  PRIMARY KEY (USERNAME)
);
create TABLE INT_PARAMS (
  PARAM_NAME VARCHAR(10) not null,
  PARAM_VALUE INTEGER,
  PRIMARY KEY (PARAM_NAME)
);
create TABLE PLAYER (
  USERNAME CHARACTER(10) not null,
  BALANCE_VERSION INTEGER not null,
  BALANCE BIGINT not null,
  PRIMARY KEY (USERNAME)
);